TEAMS = {
    'atlanta hawks': {'full_name': 'Atlanta Hawks', 'slug': 'atlanta-hawks'},
    'atl': {'full_name': 'Atlanta Hawks', 'slug': 'atlanta-hawks'},
    'boston celtics': {'full_name': 'Boston Celtics', 'slug': 'boston-celtics'},
    'bos': {'full_name': 'Boston Celtics', 'slug': 'boston-celtics'},
    'brooklyn nets': {'full_name': 'Brooklyn Nets', 'slug': 'brooklyn-nets'},
    'bkn': {'full_name': 'Brooklyn Nets', 'slug': 'brooklyn-nets'},
    'charlotte hornets': {'full_name': 'Charlotte Hornets', 'slug': 'charlotte-hornets'},
    'cha': {'full_name': 'Charlotte Hornets', 'slug': 'charlotte-hornets'},
    'chicago bulls': {'full_name': 'Chicago Bulls', 'slug': 'chicago-bulls'},
    'chi': {'full_name': 'Chicago Bulls', 'slug': 'chicago-bulls'},
    'cleveland cavaliers': {'full_name': 'Cleveland Cavaliers', 'slug': 'cleveland-cavaliers'},
    'cle': {'full_name': 'Cleveland Cavaliers', 'slug': 'cleveland-cavaliers'},
    'dallas mavericks' : {'full_name': 'Dallas Mavericks', 'slug': 'dallas-mavericks'},
    'dal': {'full_name': 'Dallas Mavericks', 'slug': 'dallas-mavericks'},
    'denver nuggets': {'full_name': 'Denver Nuggets', 'slug': 'denver-nuggets'},
    'den': {'full_name': 'Denver Nuggets', 'slug': 'denver-nuggets'},
    'detroit pistons': {'full_name': 'Detroit Pistons', 'slug': 'detroit-pistons'},
    'det': {'full_name': 'Detroit Pistons', 'slug': 'detroit-pistons'},
    'golden state warriors': {'full_name': 'Golden State Warriors', 'slug': 'golden-state-warriors'},
    'gsw': {'full_name': 'Golden State Warriors', 'slug': 'golden-state-warriors'},
    'houston rockets': {'full_name': 'Houston Rockets', 'slug': 'houston-rockets'},
    'hou': {'full_name': 'Houston Rockets', 'slug': 'houston-rockets'},
    'indiana pacers': {'full_name': 'Indiana Pacers', 'slug': 'indiana-pacers'},
    'ind': {'full_name': 'Indiana Pacers', 'slug': 'indiana-pacers'},
    'los angeles clippers': {'full_name': 'Los Angeles Clippers', 'slug': 'los-angeles-clippers'},
    'lac': {'full_name': 'Los Angeles Clippers', 'slug': 'los-angeles-clippers'},
    'los angeles lakers': {'full_name': 'Los Angeles Lakers', 'slug': 'los-angeles-lakers'},
    'lal': {'full_name': 'Los Angeles Lakers', 'slug': 'los-angeles-lakers'},
    'memphis grizzlies': {'full_name': 'Memphis Grizzlies', 'slug': 'memphis-grizzlies'},
    'mem': {'full_name': 'Memphis Grizzlies', 'slug': 'memphis-grizzlies'},
    'miami heat': {'full_name': 'Miami Heat', 'slug': 'miami-heat'},
    'mia': {'full_name': 'Miami Heat', 'slug': 'miami-heat'},
    'milwaukee bucks': {'full_name': 'Milwaukee Bucks', 'slug': 'milwaukee-bucks'},
    'mil': {'full_name': 'Milwaukee Bucks', 'slug': 'milwaukee-bucks'},
    'minnesota timberwolves': {'full_name': 'Minnesota Timberwolves', 'slug': 'minnesota-timberwolves'},
    'min': {'full_name': 'Minnesota Timberwolves', 'slug': 'minnesota-timberwolves'},
    'new orleans pelicans': {'full_name': 'New Orleans Pelicans', 'slug': 'new-orleans-pelicans'},
    'nop': {'full_name': 'New Orleans Pelicans', 'slug': 'new-orleans-pelicans'},
    'new york knicks': {'full_name': 'New York Knicks', 'slug': 'new-york-knicks'},
    'nyk': {'full_name': 'New York Knicks', 'slug': 'new-york-knicks'},
    'oklahoma city thunder': {'full_name': 'Oklahoma City Thunder', 'slug': 'oklahoma-city-thunder'},
    'okc': {'full_name': 'Oklahoma City Thunder', 'slug': 'oklahoma-city-thunder'},
    'orlando magic': {'full_name': 'Orlando Magic', 'slug': 'orlando-magic'},
    'orl': {'full_name': 'Orlando Magic', 'slug': 'orlando-magic'},
    'philadelphia 76ers': {'full_name': 'Philadelphia 76ers', 'slug': 'philadelphia-76ers'},
    'phi': {'full_name': 'Philadelphia 76ers', 'slug': 'philadelphia-76ers'},
    'phoenix suns': {'full_name': 'Phoenix Suns', 'slug': 'phoenix-suns'},
    'phx': {'full_name': 'Phoenix Suns', 'slug': 'phoenix-suns'},
    'portland trail blazers': {'full_name': 'Portland Trail Blazers', 'slug': 'portland-trail-blazers'},
    'por': {'full_name': 'Portland Trail Blazers', 'slug': 'portland-trail-blazers'},
    'sacramento kings': {'full_name': 'Sacramento Kings', 'slug': 'sacramento-kings'},
    'sac': {'full_name': 'Sacramento Kings', 'slug': 'sacramento-kings'},
    'san antonio spurs': {'full_name': 'San Antonio Spurs', 'slug': 'san-antonio-spurs'},
    'sas': {'full_name': 'San Antonio Spurs', 'slug': 'san-antonio-spurs'},
    'toronto raptors': {'full_name': 'Toronto Raptors', 'slug': 'toronto-raptors'},
    'tor': {'full_name': 'Toronto Raptors', 'slug': 'toronto-raptors'},
    'utah jazz': {'full_name': 'Utah Jazz', 'slug': 'utah-jazz'},
    'uta': {'full_name': 'Utah Jazz', 'slug': 'utah-jazz'},
    'washington-wizards': {'full_name': 'Washington Wizards', 'slug': 'washington-wizards'},
    'was': {'full_name': 'Washington Wizards', 'slug': 'washington-wizards'}
    }

BASE_URL = 'https://www.spotrac.com/nba/'